## 1. Problem Analysis

The use case involve a Covid-19 dataset. The dataset needs further prediction in order to help patients predict if they have covid-19 or not. The problem statement is to model the dataset and create an application that allows patients to input their symptoms and predict whether they have COVID or not.

## 2. Description of the dataset

The dataset has various rows and columns. The dataset has `test_date`, `cough`, `fever`, `sore_throat`, `shortness_of_breath`, `headache`, `corona_result`, `age_above_60`, `gender` and `test_indication`. The covid symptoms has value for `0` if the test turns out negative and `1` if the test is positive. If all the sysmptoms indicates `0` then the patient is `negative`. If one or two symptoms has `1` the overall results indicates `negative`. If three or all the sysmptoms indicate `1` then the patient is `positive`. The gender column has either `male` or `female`. It has some noisy data which we'll clean in the next chapter.

## 3. Data preparation and preprocessing

This is use to convert raw and noisy data into a clean data set.
In this stage we have to:

    a. Importing the libraries
    b. Importing the Dataset
    c. Handling of Missing Data
    d. Handling of Categorical Data
    e. Splitting the dataset into training and testing datasets
    f. Feature Scaling

In [44]:
#libraries
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('data.csv')
df = df.drop(columns='test_date')
df = df.drop(columns='test_indication')

df = df[df.cough != 'None']
df = df[df.fever != 'None']
df = df[df.sore_throat != 'None']
df = df[df.shortness_of_breath != 'None']
df = df[df.head_ache != 'None']


df = df[df.age_60_and_above != 'None']
df = df[df.gender != 'None']

df = df[df.corona_result != 'other']

df.to_csv('output.csv', index=False, encoding='utf8')
df.head(50)

,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender
122808,1,0,0,0,0,negative,Yes,male
122809,1,0,0,0,0,positive,No,female
122810,0,0,0,0,0,negative,No,female
122811,0,1,0,0,0,negative,No,female
122812,1,0,0,0,0,negative,Yes,female
122813,0,0,0,0,0,positive,No,male
122814,0,0,0,0,0,negative,No,female
122815,1,0,0,0,0,positive,No,female
122816,0,0,0,0,0,negative,No,female
122817,0,0,0,0,0,negative,No,female
122818,0,0,0,0,0,negative,No,female
122819,1,0,0,0,0,negative,Yes,female
122820,0,0,0,0,0,negative,No,male
122823,1,1,1,0,0,negative,No,male
122824,0,0,0,0,0,negative,No,male
122825,1,1,0,0,0,negative,Yes,male
122826,0,0,0,0,0,negative,No,male
122827,0,0,0,0,0,negative,No,male
122828,0,1,0,0,1,positive,No,female
122829,0,1,0,0,0,positive,No,male
122830,0,0,0,0,0,negative,No,female
122831,0,0,0,0,0,negative,No,male
122832,0,0,0,0,0,negative,No,female
122833,0,0,0,0,0,negative,Yes,male
122834,0,0,0,0,0,negative,No,male
122835,1,0,0,0,0,negative,No,male
122836,0,0,0,0,0,negative,No,female
122837,0,0,0,0,0,negative,No,female
122838,1,0,0,0,0,negative,No,female
122839,1,0,0,0,0,positive,No,female
122840,1,0,0,0,0,positive,No,male
122841,1,0,0,0,0,negative,Yes,male
122842,1,0,0,0,0,negative,No,male
122843,1,1,0,0,0,positive,No,female
122844,0,0,0,0,0,negative,No,male
122845,0,0,0,0,0,negative,No,female
122846,1,1,0,0,0,negative,No,male
122847,1,0,0,0,0,positive,No,male
122848,1,0,0,0,0,negative,Yes,male
122849,1,0,0,0,0,negative,No,female
122850,1,0,0,0,0,negative,No,female
122851,1,1,0,0,0,negative,Yes,male
122852,1,1,0,0,0,negative,No,male
122853,1,1,0,0,0,positive,No,female
122854,1,1,0,0,0,negative,No,female
122855,0,0,0,0,0,negative,No,male
122856,1,1,0,0,0,negative,No,male
122857,0,0,0,0,0,negative,No,female
122858,0,0,0,0,0,negative,No,female
122859,1,0,0,0,0,negative,No,male

## 4. Data Visualization
In this chapter, we'll try and visualize our cleaned dataset py plotting various columns and rows against each other.

In [ ]:
from matplotlib.pyplot import plt